[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "agora"
version = "0.1.0"
description = "Réservation automatique de créneaux sur Agora Plus"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "google-api-python-client>=2.200.0",
    "google-auth-httplib2>=0.4.2",
    "google-auth-oauthlib>=1.4.1",
    "patchright>=1.61.2",
    "pillow>=12.3.0",
    "playwright>=1.62.0",
    "pwdlib[argon2]>=0.3.1",
    "pydantic-settings>=2.14.2",
    "pyjwt>=2.13.0",
    "requests>=2.34.2",
    "tqdm>=4.70.0",
    "typer>=0.27.1",
]

[project.optional-dependencies]
stubs = [
    "types-requests>=2.33.0.20260712",
]
docs = [
    "mkdocs-material>=9.7.7",
]

[project.urls]
"Homepage" = "https://github.com/jonasrenault/agora#readme"
"Repository" = "https://github.com/jonasrenault/agora"

[project.scripts]
agora = "agora.cli.main:app"

[dependency-groups]
dev = [
    "black>=26.5.1",
    "mypy>=2.3.0",
    "pre-commit>=4.6.1",
    "pytest>=9.1.1",
    "ruff>=0.16.1",
]

[tool.black]
line_length = 90
target_version = ['py312']

[tool.ruff]
exclude = [
    ".venv",
    ".git",
    "__pycache__",
    "build",
    "dist",
    "venv",
]
src = ["agora", "tests"]
line-length = 90

[tool.ruff.lint]
ignore = []
select = [
    "E",
    "F",
    "W",
    "I001",
]

[tool.ruff.lint.isort]
known-first-party = ["agora"]

[tool.mypy]
files = ["agora", "tests"]
disable_error_code = ["import-untyped"]

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::UserWarning",
    'ignore::DeprecationWarning',
]

[tool.fastapi]
entrypoint = "agora.api.main:app"
